### ISSUE TITLE
References to `--t-rc-primary`  should probably be replaced with `--nz-rc-accent`

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/nezu#3]
There are 7 references to `--t-rc-primary` (outside of `vars.css`). They should probably be replaced with `--nz-rc-accent` in order to produce correct dark mode behaviour.

**Comment by michaellenaghan** [comment]
There are also two references to `--t-on-primary` that should probably be replaced with `--nz-rc-base`? (Less sure about that one.)

**Comment by michaellenaghan** [comment]
I also added this rule to `tags.css` to make the hashmarks visible in dark mode on hover:

```css
.entry-tags a:hover:before {
  color: rgba(var(--nz-rc-base), 0.28);
}
```
